---
- name: Fetch Syncthing configuration
  fetch:
    src="{{syncthing_user_home}}/{{syncthing_config_directory}}/{{item}}"
    dest="{{syncthing_fetch_dir}}"
    fail_on_missing=yes
  with_items:
    - "cert.pem"
    - "key.pem"
    - "config.xml"
    - "https-cert.pem"
    - "https-key.pem"
