---
- name: Reset local configuration
  ansible.builtin.file:
    path: "{{ syncthing_user_home }}/{{ syncthing_config_directory }}/{{ item }}"
    state: absent
  with_items:
    - cert.pem
    - key.pem
    - https-cert.pem
    - https-key.pem
    - config.xml
  notify: Restart Syncthing # Restart to regenerate files

- name: Populate service facts
  ansible.builtin.service_facts:

# - name: Print service facts
#   ansible.builtin.debug:
#     var: ansible_facts.services

- name: If Syncthing service exists, restart it to regenerate Syncthing configuration files
  ansible.builtin.systemd_service:
    name: syncthing.service
    state: restarted
  when: ansible_facts['services']['syncthing.service']['status'] | default('not-found') != 'not-found'
