---
- name: Add syncthing user
  ansible.builtin.user:
    name: "{{ syncthing_user }}"
    shell: "/usr/sbin/nologin"
    password: "!"
    system: true
    createhome: true
    home: "{{ syncthing_user_home }}"
  when: "syncthing_manage_user"

- name: Add syncthing repository key
  ansible.builtin.apt_key:
    url: "{{ _syncthing_apt_key_url }}"
    keyring: "{{ _syncthing_apt_key_path }}"

- name: Add syncthing repository
  ansible.builtin.apt_repository:
    repo: "{{ _syncthing_apt_repository }}"

- name: Install syncthing package
  ansible.builtin.apt:
    name: syncthing

- name: Copy syncthing systemd service
  ansible.builtin.copy:
    src: "/usr/lib/systemd/user/syncthing.service"
    dest: "/etc/systemd/system/syncthing.service"
    remote_src: true
    owner: "root"
    group: "root"
    mode: "0644"

- name: Ensure systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/syncthing.service.d
    state: directory
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set syncthing user override
  ansible.builtin.copy:
    dest: /etc/systemd/system/syncthing.service.d/override.conf
    content: |
      [Service]
      User={{ syncthing_user }}
    owner: root
    group: root
    mode: '0644'

- name: Reload systemctl
  ansible.builtin.systemd:
    daemon-reload: true

- name: Start syncthing
  ansible.builtin.service:
    name: "syncthing"
    state: "started"
    enabled: true
  when: not ansible_check_mode
